name: Solicitud de desarrollo
description: Usar para describir tareas o funcionalidades a implementar
title: "[Funcionalidad]: Implementar sistema de préstamos concurrente"
labels: ["enhancement"]
assignees: []

body:
  - type: textarea
    id: descripcion
    attributes:
      label: Descripción
      description: Describe brevemente la funcionalidad a implementar.
      placeholder: Crear el sistema de préstamos que utilice hilos y el patrón productor-consumidor para procesar solicitudes de préstamo en tiempo real.
    validations:
      required: true

  - type: textarea
    id: requisitos
    attributes:
      label: Requisitos
      description: Lista de requerimientos técnicos o funcionales.
      placeholder: |
        - Implementar `BlockingQueue` para solicitudes de préstamo
        - Crear procesador de solicitudes usando `ExecutorService`
        - Implementar sistema de notificaciones
        - Asegurar thread-safety en operaciones de préstamo
    validations:
      required: true

  - type: textarea
    id: criterios
    attributes:
      label: Criterios de Aceptación
      description: Ingresá las condiciones que debe cumplir esta funcionalidad para considerarse terminada.
      placeholder: |
        - [ ] El sistema procesa préstamos concurrentemente
        - [ ] Manejo adecuado de excepciones
        - [ ] Documentación actualizada
    validations:
      required: false
